### ISSUE TITLE
这个项目存在以下问题，望修复！

### ISSUE THREAD

**Issue by xiaoyiweb** [79E/ChatGpt-Web#102]
1、在iPhone上，签到日历显示NAN，建议将yyyy-mm-dd写法改为yyyy/mm/dd，可兼容iPhone
2、AI插件安装后，对话反应速度下降，建议优化
3、额度建议在对话完后调接口实时刷新
4、登录页面图标未对齐、用户协议及隐私协议换行了
5、ai绘画使用中转api报500

**Comment by lambxk** [comment]
你好可以请教一下你是根据哪个教程搭建的吗

**Comment by xiaoyiweb** [comment]
私信 2079157380 &nbsp;QQ




小易
***@***.***




------------------ 原始邮件 ------------------
发件人: lambxk ***@***.***&gt;
发送时间: 2023年12月5日 18:55
收件人: 79E/ChatGpt-Web ***@***.***&gt;
抄送: 小易 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [79E/ChatGpt-Web] 这个项目存在以下问题，望修复！ (Issue #102)





 
你好可以请教一下你是根据哪个教程搭建的吗
