### ISSUE TITLE
关于调用gpt api sse响应掉字的问题

### ISSUE THREAD

**Issue by dengengdeng3** [79E/ChatGpt-Web#104]
很多时候gpt 以sse方式回复问题时总是出现少字的情况。比如回复：“爱情是人类最好的情感之一，它是一种无私、纯粹的情，能够让人们感受到生命的温和幸。爱情是一种奇妙的力量，它能让人们变得勇敢、强，意为对方付一切。”掉了很多字不知道是什么情况，查看sse原始json 确实没有响应对于字的json.麻烦大佬告知一下是什么问题导致的。

**Comment by jayecho51** [comment]
加缓冲拼接
