### ISSUE TITLE
如何设置自己的api key 还有注册短信用不了

### ISSUE THREAD

**Issue by ywh888** [79E/ChatGpt-Web#14]

**Comment by 79W** [comment]
你可以在配置文件中 
```
VITE_APP_MODE=proxy
```
设置为代理模式 后在进行打包部署即可
部署完成后就可以在 设置里面进行添加你的key了

**Comment by ywh888** [comment]
不在页面显示，直接在后台内置，还有就是短信一直无法获取，需要怎么配置吗

**Comment by ywh888** [comment]
![image](https://user-images.githubusercontent.com/35958060/236623735-38b58ad2-32ba-4c97-ab9c-0746496d61ac.png)
如何配置会员功能 对次数的限制 在那个文件进行配置呢

**Comment by 79E** [comment]
> ![image](https://user-images.githubusercontent.com/35958060/236623735-38b58ad2-32ba-4c97-ab9c-0746496d61ac.png) 如何配置会员功能 对次数的限制 在那个文件进行配置呢

可以看
```
.env.production
```
这个文件 这里面有一些配置 目前服务端的代码没有公开 因为比较简单和不完善
