### ISSUE TITLE
想问一下后端是否会开源？

### ISSUE THREAD

**Issue by SwaggyMacro** [79E/ChatGpt-Web#34]
😋礼貌性的问一下，如题。

**Comment by 79W** [comment]
> 😋礼貌性的问一下，如题。

会开源 现在还不是很完善 也没有整理 
可以先按照 [接口文档](https://console-docs.apipost.cn/preview/dcf9a900ac5a1154/00eeb0b3f589d8e6) 编写你自己的服务端

**Comment by SwaggyMacro** [comment]
OKOK，谢谢。
