### ISSUE TITLE
合作开发拓展项目

### ISSUE THREAD

**Issue by qcl006007** [79E/ChatGpt-Web#36]
开发一名，后端技术栈为.NET 和 Nodejs， Next, 前端主要为angular, vue2 和 react 写的不多；

感觉前端比较页面已经比较成熟，自己目前在实现后端接口，主要使用nodejs 和 mongodb， 

自己已实现
    chat, 
    画图（dall2 和 midjourney model） ，
    用户存储，
    token的中间件认证

在使用中发现部分功能已经实现，想询问是否还需要人员一起合作这个项目？

可以帮助开发后端api，搭建海外代理转发服务器；

考虑扩展功能，对标chatPDF, 读取文件帮助回答；

数据库的相关 ......

如可以，考虑加微信细聊，已对项目进行赞赏过并备注。

**Comment by 79W** [comment]
赞赏留微
