### ISSUE TITLE
商业模式新建对话，并不会新增parentMessageId

### ISSUE THREAD

**Issue by dringer123** [79E/ChatGpt-Web#38]
无论新建多少个对话，有效的parentMessageId只有一个，导致我后端都不知道怎么写？除了第一个会话会携带parentMessageId，其他会话都是空的，有点迷惑，这样就不知道怎么判断用户当前对话的是哪个id了，chatgpt恢复也混乱 了起来

**Comment by 79W** [comment]
我看下 好像确实有这个问题 我今天修复一下

**Comment by dringer123** [comment]
感谢您回复
在测试时还遇到个小问题，就是系统配置修改时没有携带修改后的一些参数
<img width="1616" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/2d2f5418-80dc-4add-acdf-c699a38d88b6">

**Comment by 79E** [comment]
已经都修复可以看下 v1.0.1 版本 这个我就关闭了有问题在重新提交

**Comment by dringer123** [comment]
大佬牛逼啊，顶礼膜拜
