### ISSUE TITLE
新版本1.01测试时遇到的一些问题

### ISSUE THREAD

**Issue by dringer123** [79E/ChatGpt-Web#39]
1、右上角刷新余额不显示
<img width="988" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/c60d91a3-4f70-45b5-8bef-d958132ce9b9">
2、退出登录后本地session没销毁，除非清除本地session否则重新登录会跳转404（不确定，怀疑本地没有更新session）
3、gpt对话时响应不显示，响应start时会转圈，响应text时显示一个空气泡和响应stop时一样，如下图
<img width="1416" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/74cb13ff-2e1e-4432-8914-1556732fedb2">
<img width="1433" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/26b5187b-652a-4c00-8376-0bc3c8f5c33d">
4、小建议，只设置一个stop即可，由前端接收后逐渐输出全部内容（而不是像1.0版本之前一股脑输出）

**Comment by 79W** [comment]
1.  我看你的响应结构不正确
2. 我这边没有遇到那个问题 可以给我提供录屏或者更详细的
3. 响应错误后需处理 这块我在完善下 
4. 已经设置服务器状态

**Comment by dringer123** [comment]
抱歉，原来integral参数才是余额，增加后已经可以显示了。
我看的api文档没更新，还是几天前的，今天看了新的文档，1,2，已经解决了
不过有个问题还是想请教下，或许我的对对话处理不是很好：
<img width="578" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/2fd03f10-a169-411f-a2d2-7d9c18ebac3a">
POST对话我看您的文档写的是start|text|stop
请问这三个响应需要一起返回给客户端吗？还是有某种功能使得客户端请求一次服务端可以连续响应三次？
或者是openAI那种流式传输？
我尝试将三个响应一起返回给客户端（就像开起了stream流式传输的openai返回给我的一样，但是貌似不生效

有点迷惑，对于客户端调试这块不是很了解，所以只能自己一步步试，还望解答！

**Comment by SwaggyMacro** [comment]
> 抱歉，原来integral参数才是余额，增加后已经可以显示了。 我看的api文档没更新，还是几天前的，今天看了新的文档，1,2，已经解决了 不过有个问题还是想请教下，或许我的对对话处理不是很好： <img alt="image" width="578" src="https://user-images.githubusercontent.com/47192426/239745366-2fd03f10-a169-411f-a2d2-7d9c18ebac3a.png"> POST对话我看您的文档写的是start|text|stop 请问这三个响应需要一起返回给客户端吗？还是有某种功能使得客户端请求一次服务端可以连续响应三次？ 或者是openAI那种流式传输？ 我尝试将三个响应一起返回给客户端（就像开起了stream流式传输的openai返回给我的一样，但是貌似不生效
> 
> 有点迷惑，对于客户端调试这块不是很了解，所以只能自己一步步试，还望解答！

第一次response的segment 填 start，之后的response都给text，最后一次response给stop，每次返回用\n分割。

**Comment by 79W** [comment]
> > 抱歉，原来integral参数才是余额，增加后已经可以显示了。 我看的api文档没更新，还是几天前的，今天看了新的文档，1,2，已经解决了 不过有个问题还是想请教下，或许我的对对话处理不是很好： <img alt="image" width="578" src="https://user-images.githubusercontent.com/47192426/239745366-2fd03f10-a169-411f-a2d2-7d9c18ebac3a.png"> POST对话我看您的文档写的是start|text|stop 请问这三个响应需要一起返回给客户端吗？还是有某种功能使得客户端请求一次服务端可以连续响应三次？ 或者是openAI那种流式传输？ 我尝试将三个响应一起返回给客户端（就像开起了stream流式传输的openai返回给我的一样，但是貌似不生效
> > 有点迷惑，对于客户端调试这块不是很了解，所以只能自己一步步试，还望解答！
> 
> 第一次response的segment 填 start，之后的response都给text，最后一次response给stop，每次返回用\n分割。

对的 是 返回的流 第一次返回 start 中间是内容所以返回 text 最后结束了 返回stop

**Comment by dringer123** [comment]
> > > 抱紧，原来积分参数才是余额，增加后已经可以显示了。我看的api文档没有更新，还是前几天的，今天看了新的文档，1,2，已解释决定了不过有一个问题还是想请教下，或者也许我的对话处理不是很好：<img alt="图像" width="578" src="https://user-images.githubusercontent.com/47192426/239745366-2fd03f10-a169-411f-a2d2-7d9c18ebac3a.png">POST对话我看您的文档写的是start|text|stop 请问这三个响应需要一起返回给客户端吗？还是有某种功能使客人端请求一次服务端可以连续响应三次吗？ 或者对方是openAI那种流式传输？流式传输的openai返回给我的一样，但是貌似无效
> > > 有点迷惑，对于客户端调试这块不太明白，所以只能自己一步试，还望解答！
> > 
> > 
> > 第一次响应的段填开始，之后的响应都给文本，最后一次响应给停止，每次返回用\n分割。
> 
> 对的是返回的流 第一次返回 start 中间是内容所以返回 text 最后结束束了 返回stop

明白了，流式传输的话那我就不能把三个内容一起写进响应体了，我需要去学习下，感谢解答

**Comment by dringer123** [comment]
<img width="1200" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/0e96825a-76ac-4579-93f8-0561ce7b4071">
请问角色预设在选择成功后 需要一些别的操作吗，我选择充当linux终端后我的下一次提交没有作用，就像这样
<img width="961" alt="image" src="https://github.com/79E/ChatGpt-Web/assets/47192426/8ad779b4-dd59-49a0-8e88-5557375148f1">

**Comment by 79W** [comment]
> <img alt="image" width="1200" src="https://user-images.githubusercontent.com/47192426/239785103-0e96825a-76ac-4579-93f8-0561ce7b4071.png"> 请问角色预设在选择成功后 需要一些别的操作吗，我选择充当linux终端后我的下一次提交没有作用，就像这样 <img alt="image" width="961" src="https://user-images.githubusercontent.com/47192426/239785329-8ad779b4-dd59-49a0-8e88-5557375148f1.png">

你新创建个 会话 然后好好读下 中间的文字 就明白了

**Comment by dringer123** [comment]
> > <img alt="image" width="1200" src="https://user-images.githubusercontent.com/47192426/239785103-0e96825a-76ac-4579-93f8-0561ce7b4071.png"> 请问角色预设在选择成功后 需要一些别的操作吗，我选择充当linux终端后我的下一次提交没有作用，就像这样 <img alt="image" width="961" src="https://user-images.githubusercontent.com/47192426/239785329-8ad779b4-dd59-49a0-8e88-5557375148f1.png">
> 
> 你新创建个 会话 然后好好读下 中间的文字 就明白了

好的。看到了！
