### ISSUE TITLE
这是纯前端项目吗？

### ISSUE THREAD

**Issue by gaye746560359** [79E/ChatGpt-Web#43]
1.部署后登录注册提示网络错误
2.没有看到后端的配置，像数据库之类的配置，是要自己跟前端的接口参数，实现后端吗？

**Comment by 79W** [comment]
后端已经快写完还没有开源。目前只是前端开源了
接口文档已经提供可以自己 先实现下 或者联系我

**Comment by gaye746560359** [comment]
> 后端已经快写完还没有开源。目前只是前端开源了 接口文档已经提供可以自己 先实现下 或者联系我

后端是python吗？还是其他语言

**Comment by 79W** [comment]
> python

go 和 nodejs

**Comment by HKJ666** [comment]
哥加下v

**Comment by 79W** [comment]
> 哥加下v

打赏 备注你v 我加
