### ISSUE TITLE
111

### ISSUE THREAD

**Issue by nianbangzi** [79E/ChatGpt-Web#46]
14:18:51.554 已拦截加载自“http://xxxx.com/src/main.tsx”的模块，它使用了不允许的 MIME 类型（“application/octet-stream”）。

**Comment by 79W** [comment]
？

**Comment by 79W** [comment]
你这直接跑 ts 你怎么能跑起来 。。。

**Comment by nianbangzi** [comment]
我也不晓得，按照教程一步步来的，然后控制台就报错了，纯小白不太懂

**Comment by 79W** [comment]
先学习学习基础。。。 关了哈
