### ISSUE TITLE
首页注册失败，提示网络异常

### ISSUE THREAD

**Issue by cdssd** [79E/ChatGpt-Web#52]
yarn install
yarn dev:web

打开网页注册，提示网络故障
![微信图片_20230526151850](https://github.com/79E/ChatGpt-Web/assets/116550571/2f33f7ce-6507-4495-9de5-2e55800c8a11)

**Comment by dringer123** [comment]
> yarn install yarn dev:web
> 
> 打开网页注册，提示网络故障 ![微信图片_20230526151850](https://user-images.githubusercontent.com/116550571/241147460-2f33f7ce-6507-4495-9de5-2e55800c8a11.png)

这只是个前端，后端需要自己写的，api文档作者已经贴出来了
