### ISSUE TITLE
搭建教程

### ISSUE THREAD

**Issue by Rockney99** [79E/ChatGpt-Web#62]
不好意思 我搭建出了点问题或者文档看的不是懂 想问一下我用宝塔面板搭建的具体流程 我是在发布里下载好直接上传到宝塔网站目录的 访问不了 在我搭建完成后我想顺手提供个详细的搭建文档给和我一样看不懂的朋友能看懂怎么搭建

**Comment by 7275808474** [comment]
能发下搭建教程吗
