### ISSUE TITLE
搭建好以后，前端一直提示--网络异常，请稍后重新尝试。

### ISSUE THREAD

**Issue by sorrelbaby** [79E/ChatGpt-Web#69]
初学者，利用宝塔搭建的，centos7.x、nginx1.22、php7.4、mysql5.7、redis7.0.11、宝塔node.js管理器。环境都OK。

前端地址-/www/wwwroot/chatGpt_v122/dist （网络异常，请稍后重新尝试。）报错

node项目地址/www/wwwroot/chatGpt_v122/（正常运行）

mysql也正常导入，node项目正常连接。

.env.development、.env.production写的node项目ssl地址。

开了一个新网站，绑定了域名，反向代理到127.0.0.1:3200上。

请教一下作者，到底哪个地方没弄对。问了chatgpt，给的答案并不适用。弄了一天没找到原因，所以希望作者能给我个学习机会，告知一下问题，我可以自己去了解下原理。

**Comment by 1113654946** [comment]
后台一键搭建的没有吗

**Comment by cdssd** [comment]
127.0.0.1 换成实ip估计能行
