### ISSUE TITLE
请问这个有后台吗？

### ISSUE THREAD

**Issue by zyoung1212** [79E/ChatGpt-Web#7]
看到商业化需要实现发送短信或邮箱验证码的功能，请问这部分有后台吗？还是需要自己实现？

**Comment by 79W** [comment]
> 看到商业化需要实现发送短信或邮箱验证码的功能，请问这部分有后台吗？还是需要自己实现？

服务端代码有但是还不完善 暂时没开源

**Comment by zyoung1212** [comment]
> 

好的，感谢，关注一下。
