### ISSUE TITLE
请问为什么对话时AI返回管理员未配置相关模型呢

### ISSUE THREAD

**Issue by Foxisnotfucks** [79E/ChatGpt-Web#74]
![1688690302253](https://github.com/79E/ChatGpt-Web/assets/57314505/7870035b-70f3-4af6-a83c-a496cebbef85)

**Comment by 79W** [comment]
你在后台配置啊

**Comment by 79W** [comment]
这是演示站吗？ 演示站我是没配置

**Comment by Foxisnotfucks** [comment]
> 你在后台配置啊

好的，很抱歉，我还想问问如何打开后台配置呢？
