### ISSUE TITLE
我用 golang 实现一套后端，欢迎试用

### ISSUE THREAD

**Issue by heimeropen** [79E/ChatGpt-Web#92]
我用 golang 实现一套后端，欢迎试用
对应最新前端代码，master/main分支
https://github.com/heimeropen/chatgpt-web-go

**Comment by 79W** [comment]
很不错！ 希望可以完善下你的文档说明的一些东西
1. 项目目录介绍 函数解释啥的
2. api文档最好弄个链接啥的 你这md看这脑袋疼

**Comment by CherishMvp** [comment]
确实,文档可优先完善一下,阅读起来会比较友好一些

**Comment by heimeropen** [comment]
感谢建议，文档已经在逐步更新
